tasks:

  - name: Install dependencies
    init: |
      gp sync-await global-node
      pnpm install
      gp sync-done deps
      exit

  - name: Install Doppler
    init: |
      sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
      curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo apt-key add -
      echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
      sudo apt-get update && sudo apt-get install doppler -y
      gp sync-done install-doppler
      exit

  - name: Logins
    command: |
      gp sync-await install-doppler
      echo $DOPPLER_SERVICE_TOKEN | doppler configure set token --scope /
      gp sync-done logins
      exit

ports:
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3005
    onOpen: ignore
  - port: 3333
    onOpen: ignore

vscode:
  extensions:
    - sperovita.alpinejs-syntax-highlight
    - adrianwilczynski.alpine-js-intellisense
    - GitHub.copilot
    - GraphQL.vscode-graphql
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - eseom.nunjucks-template
    - christian-kohler.path-intellisense
    - esbenp.prettier-vscode
    - Prisma.prisma
    - jasonnutter.search-node-modules
    - SonarSource.sonarlint-vscode
    - bradlc.vscode-tailwindcss
    - rangav.vscode-thunder-client
    - redhat.vscode-yaml
    - dbaeumer.vscode-eslint
    - GitHub.vscode-pull-request-github
