source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-seo-tag'
gem "jekyll-postcss"
gem "jekyll-minifier"

group :jekyll_plugins do
  # (other jekyll plugins)
  gem 'jekyll_picture_tag', '~> 2.0'
end