name: Mirror frontend to Neocities

on:
  workflow_call:
    secrets:
      NEOCITIES_API_KEY:
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Clean up
        run: |
          rm CNAME
          rm -rf .git
          mv 404.html not_found.html

      - name: Cloudflare Analytics
        run: |
          find -name '*.html' -exec sed -i 's|</body>|<!-- Cloudflare Web Analytics --><script defer src='\''https://static.cloudflareinsights.com/beacon.min.js'\'' data-cf-beacon='\''{"token": "ebc7fbd034354f089166b7c3c142291a"}'\''></script><!-- End Cloudflare Web Analytics --></body>|g' {} +
          find -name '*.html' -exec sed -i 's|</BODY>|<!-- Cloudflare Web Analytics --><script defer src='\''https://static.cloudflareinsights.com/beacon.min.js'\'' data-cf-beacon='\''{"token": "ebc7fbd034354f089166b7c3c142291a"}'\''></script><!-- End Cloudflare Web Analytics -->\n</BODY>|g' {} +

      - name: Mirror to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          cleanup: true
          dist_dir: .

