name: Deploy to Neocities

# only run on changes to master
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean up for Neocities
      run: |
        mkdir .public
        cp -r * .public/
        rm .public/CNAME
        mv .public public
    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@master
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
