name: Build and deploy reviews

on:
  push:
    paths:
      - "apps/reviews/**"
      - ".github/workflows/reviews.yml"
      - ".github/workflows/neocities.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: apps/reviews

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.10.0

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "16"

      - name: Get libvips
        run: |
          sudo apt-get update
          sudo apt-get install libvips-dev -y

      - name: Install and Build
        run: |
          pnpm i --filter reviews --frozen-lockfile
          npx turbo run build --scope=reviews --include-dependencies --no-deps

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: apps/reviews/_site
          target-folder: reviews

  mirror:
    needs: build-and-deploy
    uses: "./.github/workflows/neocities.yml"
    secrets:
      NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_TOKEN }}
