name: Build and deploy frontend

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"
      - ".github/workflows/neocities.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: apps/web/root

  mirror:
    needs: build-and-deploy
    uses: "./.github/workflows/neocities.yml"
    secrets:
      NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_TOKEN }}
