name: Build and deploy frontend

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          npm ci -w web -w tsconfig -w config
          npx turbo run build --scope=web --include-dependencies --no-deps

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: apps/web/dist

      - name: Clean up for Neocities
        run: |
          rm apps/web/dist/CNAME
          mv apps/web/dist/404.html apps/web/dist/not_found.html

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@master
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: apps/web/dist
          cleanup: true
          protected_files: 'reviews/**/*'
