name: Build and deploy frontend

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"
      - ".github/workflows/neocities.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.10.0

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "16"

      - name: Install and Build
        run: |
          pnpm i --filter web --frozen-lockfile
          npx turbo run build --scope=web --include-dependencies --no-deps
        env:
          VITE_FETCH_ENDPOINT: ${{ secrets.BUILD_WEB_FETCH_ENDPOINT }}
          VITE_FORM_ENDPOINT: ${{ secrets.BUILD_WEB_SUBMIT_ENDPOINT }}
          VITE_BLOG_ENDPOINT: ${{ secrets.BUILD_WEB_BLOG_ENDPOINT }}
          VITE_SENTRY_DSN: ${{ secrets.BUILD_WEB_SENTRY_DSN }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: apps/web/dist

  mirror:
    needs: build-and-deploy
    uses: "./.github/workflows/neocities.yml"
